apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-springbootapp-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app 
    spec:
      containers:
        - name: my-springboot-app 
          image: idanacrrepo4321.azurecr.io/greatking2sk/springboot-app
          ports:
          - containerPort: 80
